"""contract control plane

Revision ID: 0001
Revises:
Create Date: 2026-07-31 17:33:32.697697
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_client",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("allowed_endpoints", sa.JSON(), nullable=False),
        sa.Column("allowed_models", sa.JSON(), nullable=False),
        sa.Column("group_ids", sa.JSON(), nullable=False),
        sa.Column("qps_limit", sa.Integer(), nullable=False),
        sa.Column("concurrency_limit", sa.Integer(), nullable=False),
        sa.Column("daily_request_limit", sa.BigInteger(), nullable=True),
        sa.Column("daily_token_limit", sa.BigInteger(), nullable=True),
        sa.Column("total_request_limit", sa.BigInteger(), nullable=True),
        sa.Column("total_token_limit", sa.BigInteger(), nullable=True),
        sa.Column("max_output_tokens_per_request", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("updated_by", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("disabled_at", sa.BigInteger(), nullable=True),
        sa.Column("archived_at", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("status IN ('active', 'disabled', 'archived')", name=op.f("ck_api_client_status_values")),
        sa.CheckConstraint("concurrency_limit > 0", name=op.f("ck_api_client_concurrency_positive")),
        sa.CheckConstraint(
            "daily_request_limit IS NULL OR daily_request_limit > 0", name=op.f("ck_api_client_daily_requests_positive")
        ),
        sa.CheckConstraint(
            "daily_token_limit IS NULL OR daily_token_limit > 0", name=op.f("ck_api_client_daily_tokens_positive")
        ),
        sa.CheckConstraint(
            "description IS NULL OR length(description) <= 1024", name=op.f("ck_api_client_description_length")
        ),
        sa.CheckConstraint("length(name) BETWEEN 1 AND 128", name=op.f("ck_api_client_name_length")),
        sa.CheckConstraint("max_output_tokens_per_request > 0", name=op.f("ck_api_client_max_output_tokens_positive")),
        sa.CheckConstraint("qps_limit > 0", name=op.f("ck_api_client_qps_positive")),
        sa.CheckConstraint(
            "total_request_limit IS NULL OR total_request_limit > 0", name=op.f("ck_api_client_total_requests_positive")
        ),
        sa.CheckConstraint(
            "total_token_limit IS NULL OR total_token_limit > 0", name=op.f("ck_api_client_total_tokens_positive")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_api_client_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_client")),
        sa.UniqueConstraint("name", name="uq_api_client_name"),
    )
    with op.batch_alter_table("api_client", schema=None) as batch_op:
        batch_op.create_index("ix_api_client_status_name", ["status", "name"], unique=False)

    op.create_table(
        "api_client_admin_audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=128), nullable=False),
        sa.Column("api_client_id", sa.String(length=36), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("before_summary", sa.JSON(), nullable=False),
        sa.Column("after_summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("length(action) BETWEEN 1 AND 64", name=op.f("ck_api_client_admin_audit_action_length")),
        sa.CheckConstraint(
            "length(actor_user_id) BETWEEN 1 AND 128", name=op.f("ck_api_client_admin_audit_actor_user_id_length")
        ),
        sa.CheckConstraint(
            "target_id IS NULL OR length(target_id) BETWEEN 1 AND 128",
            name=op.f("ck_api_client_admin_audit_target_id_length"),
        ),
        sa.CheckConstraint(
            "target_type IN ('client', 'credential', 'permission', 'quota', 'group', 'status', 'retention', 'export')",
            name=op.f("ck_api_client_admin_audit_target_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_client_admin_audit_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_client_admin_audit")),
    )
    with op.batch_alter_table("api_client_admin_audit", schema=None) as batch_op:
        batch_op.create_index(
            "ix_api_client_admin_audit_api_client_created", ["api_client_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "control_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("target", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.BigInteger(), nullable=False),
        sa.Column("locked_at", sa.BigInteger(), nullable=True),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "action IN ('create', 'update', 'disable', 'compensate')", name=op.f("ck_control_outbox_action_values")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')", name=op.f("ck_control_outbox_status_values")
        ),
        sa.CheckConstraint("target IN ('bifrost', 'openwebui')", name=op.f("ck_control_outbox_target_values")),
        sa.CheckConstraint("attempt_count BETWEEN 0 AND 1000", name=op.f("ck_control_outbox_attempt_count_bounds")),
        sa.CheckConstraint(
            "last_error_code IS NULL OR length(last_error_code) <= 64", name=op.f("ck_control_outbox_error_code_length")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_outbox")),
        sa.UniqueConstraint("idempotency_key", name="uq_control_outbox_idempotency_key"),
    )
    with op.batch_alter_table("control_outbox", schema=None) as batch_op:
        batch_op.create_index("ix_control_outbox_aggregate", ["aggregate_type", "aggregate_id"], unique=False)
        batch_op.create_index(
            "ix_control_outbox_target_status_available", ["target", "status", "available_at", "id"], unique=False
        )

    op.create_table(
        "api_client_binding",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("api_client_id", sa.String(length=36), nullable=False),
        sa.Column("zangpu_service_user_id", sa.String(length=128), nullable=True),
        sa.Column("bifrost_virtual_key_id", sa.String(length=128), nullable=True),
        sa.Column("bifrost_value_ciphertext", sa.Text(), nullable=True),
        sa.Column("bifrost_value_key_version", sa.String(length=64), nullable=True),
        sa.Column("bifrost_config_hash", sa.String(length=128), nullable=False),
        sa.Column("sync_status", sa.String(length=16), nullable=False),
        sa.Column("last_sync_error_code", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "sync_status IN ('pending', 'active', 'disabled', 'error')",
            name=op.f("ck_api_client_binding_sync_status_values"),
        ),
        sa.CheckConstraint(
            "sync_status NOT IN ('active', 'disabled') OR "
            "(zangpu_service_user_id IS NOT NULL AND bifrost_virtual_key_id IS NOT NULL AND "
            "bifrost_value_ciphertext IS NOT NULL AND bifrost_value_key_version IS NOT NULL)",
            name=op.f("ck_api_client_binding_synced_remote_fields"),
        ),
        sa.CheckConstraint(
            "last_sync_error_code IS NULL OR length(last_sync_error_code) <= 64",
            name=op.f("ck_api_client_binding_error_code_length"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_api_client_binding_version_positive")),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_client_binding_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_client_binding")),
        sa.UniqueConstraint("api_client_id", name="uq_api_client_binding_api_client_id"),
        sa.UniqueConstraint("bifrost_virtual_key_id", name="uq_api_client_binding_bifrost_key_id"),
        sa.UniqueConstraint("zangpu_service_user_id", name="uq_api_client_binding_service_user_id"),
    )
    op.create_table(
        "api_client_credential",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("api_client_id", sa.String(length=36), nullable=False),
        sa.Column("key_id", sa.String(length=80), nullable=False),
        sa.Column("secret_ciphertext", sa.Text(), nullable=False),
        sa.Column("secret_nonce", sa.String(length=64), nullable=False),
        sa.Column("master_key_id", sa.String(length=64), nullable=False),
        sa.Column("secret_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=True),
        sa.Column("last_used_at", sa.BigInteger(), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("revoked_by", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("revoked_at", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("status IN ('active', 'revoked')", name=op.f("ck_api_client_credential_status_values")),
        sa.CheckConstraint(
            "expires_at IS NULL OR expires_at > 0", name=op.f("ck_api_client_credential_expires_at_positive")
        ),
        sa.CheckConstraint("length(key_id) BETWEEN 8 AND 80", name=op.f("ck_api_client_credential_key_id_length")),
        sa.CheckConstraint("substr(key_id, 1, 4) = 'zpk_'", name=op.f("ck_api_client_credential_key_id_prefix")),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_client_credential_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["api_client_credential.id"],
            name=op.f("fk_api_client_credential_replaced_by_id_api_client_credential"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_client_credential")),
        sa.UniqueConstraint("key_id", name="uq_api_client_credential_key_id"),
    )
    with op.batch_alter_table("api_client_credential", schema=None) as batch_op:
        batch_op.create_index("ix_api_client_credential_api_client_id", ["api_client_id"], unique=False)
        batch_op.create_index("ix_api_client_credential_replaced_by_id", ["replaced_by_id"], unique=False)

    op.create_table(
        "api_client_quota_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("api_client_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.BigInteger(), nullable=False),
        sa.Column("request_count", sa.BigInteger(), nullable=False),
        sa.Column("token_reserved", sa.BigInteger(), nullable=False),
        sa.Column("token_consumed", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "(scope = 'daily' AND period_start > 0) OR (scope = 'lifetime' AND period_start = 0)",
            name=op.f("ck_api_client_quota_usage_scope_period"),
        ),
        sa.CheckConstraint("scope IN ('daily', 'lifetime')", name=op.f("ck_api_client_quota_usage_scope_values")),
        sa.CheckConstraint("request_count >= 0", name=op.f("ck_api_client_quota_usage_request_count_nonnegative")),
        sa.CheckConstraint("token_consumed >= 0", name=op.f("ck_api_client_quota_usage_token_consumed_nonnegative")),
        sa.CheckConstraint("token_reserved >= 0", name=op.f("ck_api_client_quota_usage_token_reserved_nonnegative")),
        sa.CheckConstraint("version > 0", name=op.f("ck_api_client_quota_usage_version_positive")),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_client_quota_usage_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_client_quota_usage")),
        sa.UniqueConstraint("api_client_id", "scope", "period_start", name="uq_api_client_quota_scope_period"),
    )
    op.create_table(
        "api_call_operation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("api_client_id", sa.String(length=36), nullable=False),
        sa.Column("credential_id", sa.String(length=36), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reserved_tokens", sa.BigInteger(), nullable=False),
        sa.Column("prompt_tokens", sa.BigInteger(), nullable=False),
        sa.Column("completion_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("credit_settlement_id", sa.String(length=128), nullable=True),
        sa.Column("usage_operation_id", sa.String(length=128), nullable=True),
        sa.Column("terminal_http_status", sa.Integer(), nullable=True),
        sa.Column("terminal_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.BigInteger(), nullable=False),
        sa.Column("completed_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'completed', 'rejected', 'abandoned')",
            name=op.f("ck_api_call_operation_status_values"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at", name=op.f("ck_api_call_operation_completion_order")
        ),
        sa.CheckConstraint("completion_tokens >= 0", name=op.f("ck_api_call_operation_completion_tokens_nonnegative")),
        sa.CheckConstraint("prompt_tokens >= 0", name=op.f("ck_api_call_operation_prompt_tokens_nonnegative")),
        sa.CheckConstraint("reserved_tokens >= 0", name=op.f("ck_api_call_operation_reserved_tokens_nonnegative")),
        sa.CheckConstraint(
            "terminal_http_status IS NULL OR terminal_http_status BETWEEN 100 AND 599",
            name=op.f("ck_api_call_operation_http_status"),
        ),
        sa.CheckConstraint(
            "total_tokens = prompt_tokens + completion_tokens", name=op.f("ck_api_call_operation_token_total_matches")
        ),
        sa.CheckConstraint("total_tokens >= 0", name=op.f("ck_api_call_operation_total_tokens_nonnegative")),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_call_operation_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["api_client_credential.id"],
            name=op.f("fk_api_call_operation_credential_id_api_client_credential"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_call_operation")),
        sa.UniqueConstraint("api_client_id", "client_request_id", name="uq_api_call_operation_client_request"),
    )
    with op.batch_alter_table("api_call_operation", schema=None) as batch_op:
        batch_op.create_index("ix_api_call_operation_credential_id", ["credential_id"], unique=False)
        batch_op.create_index("ix_api_call_operation_status_updated", ["status", "updated_at", "id"], unique=False)

    op.create_table(
        "api_call_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("server_request_id", sa.String(length=128), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=True),
        sa.Column("api_client_id", sa.String(length=36), nullable=True),
        sa.Column("credential_id", sa.String(length=36), nullable=True),
        sa.Column("endpoint", sa.String(length=64), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=True),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("stage", sa.String(length=24), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=False),
        sa.Column("business_code", sa.String(length=64), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.BigInteger(), nullable=False),
        sa.Column("prompt_tokens", sa.BigInteger(), nullable=False),
        sa.Column("completion_tokens", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens", sa.BigInteger(), nullable=False),
        sa.Column("charged_micro", sa.BigInteger(), nullable=False),
        sa.Column("qps_observed", sa.Integer(), nullable=False),
        sa.Column("concurrency_observed", sa.Integer(), nullable=False),
        sa.Column("daily_requests_after", sa.BigInteger(), nullable=False),
        sa.Column("daily_tokens_after", sa.BigInteger(), nullable=False),
        sa.Column("total_requests_after", sa.BigInteger(), nullable=False),
        sa.Column("total_tokens_after", sa.BigInteger(), nullable=False),
        sa.Column("remote_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_family", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.BigInteger(), nullable=False),
        sa.Column("completed_at", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('success', 'cancelled', 'rejected', 'provider_error', 'system_error', 'abandoned')",
            name=op.f("ck_api_call_event_outcome_values"),
        ),
        sa.CheckConstraint(
            "stage IN ('request', 'auth', 'permission', 'rate_limit', 'quota', "
            "'credit', 'provider', 'response', 'recovery')",
            name=op.f("ck_api_call_event_stage_values"),
        ),
        sa.CheckConstraint("charged_micro >= 0", name=op.f("ck_api_call_event_charged_micro_nonnegative")),
        sa.CheckConstraint("completed_at >= started_at", name=op.f("ck_api_call_event_completion_order")),
        sa.CheckConstraint("completion_tokens >= 0", name=op.f("ck_api_call_event_completion_tokens_nonnegative")),
        sa.CheckConstraint("concurrency_observed >= 0", name=op.f("ck_api_call_event_concurrency_nonnegative")),
        sa.CheckConstraint("daily_requests_after >= 0", name=op.f("ck_api_call_event_daily_requests_nonnegative")),
        sa.CheckConstraint("daily_tokens_after >= 0", name=op.f("ck_api_call_event_daily_tokens_nonnegative")),
        sa.CheckConstraint("duration_ms >= 0", name=op.f("ck_api_call_event_duration_nonnegative")),
        sa.CheckConstraint("http_status BETWEEN 100 AND 599", name=op.f("ck_api_call_event_http_status")),
        sa.CheckConstraint("prompt_tokens >= 0", name=op.f("ck_api_call_event_prompt_tokens_nonnegative")),
        sa.CheckConstraint("qps_observed >= 0", name=op.f("ck_api_call_event_qps_nonnegative")),
        sa.CheckConstraint("total_requests_after >= 0", name=op.f("ck_api_call_event_total_requests_nonnegative")),
        sa.CheckConstraint(
            "total_tokens = prompt_tokens + completion_tokens", name=op.f("ck_api_call_event_token_total_matches")
        ),
        sa.CheckConstraint("total_tokens_after >= 0", name=op.f("ck_api_call_event_total_tokens_after_nonnegative")),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
            name=op.f("fk_api_call_event_api_client_id_api_client"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["api_client_credential.id"],
            name=op.f("fk_api_call_event_credential_id_api_client_credential"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["api_call_operation.id"],
            name=op.f("fk_api_call_event_operation_id_api_call_operation"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_call_event")),
        sa.UniqueConstraint("operation_id", name="uq_api_call_event_operation_id"),
        sa.UniqueConstraint("server_request_id", name="uq_api_call_event_server_request_id"),
    )
    with op.batch_alter_table("api_call_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_api_call_event_api_client_created", ["api_client_id", "created_at", "id"], unique=False
        )
        batch_op.create_index("ix_api_call_event_credential_id", ["credential_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_call_event", schema=None) as batch_op:
        batch_op.drop_index("ix_api_call_event_credential_id")
        batch_op.drop_index("ix_api_call_event_api_client_created")

    op.drop_table("api_call_event")
    with op.batch_alter_table("api_call_operation", schema=None) as batch_op:
        batch_op.drop_index("ix_api_call_operation_status_updated")
        batch_op.drop_index("ix_api_call_operation_credential_id")

    op.drop_table("api_call_operation")
    op.drop_table("api_client_quota_usage")
    with op.batch_alter_table("api_client_credential", schema=None) as batch_op:
        batch_op.drop_index("ix_api_client_credential_replaced_by_id")
        batch_op.drop_index("ix_api_client_credential_api_client_id")

    op.drop_table("api_client_credential")
    op.drop_table("api_client_binding")
    with op.batch_alter_table("control_outbox", schema=None) as batch_op:
        batch_op.drop_index("ix_control_outbox_target_status_available")
        batch_op.drop_index("ix_control_outbox_aggregate")

    op.drop_table("control_outbox")
    with op.batch_alter_table("api_client_admin_audit", schema=None) as batch_op:
        batch_op.drop_index("ix_api_client_admin_audit_api_client_created")

    op.drop_table("api_client_admin_audit")
    with op.batch_alter_table("api_client", schema=None) as batch_op:
        batch_op.drop_index("ix_api_client_status_name")

    op.drop_table("api_client")
    # ### end Alembic commands ###
